//REDUCER
export const GET_USER_LOGIN = 'GET_USER_LOGIN'
export const GET_LIST_USER = 'GET_LIST_USER'
export const SET_LOADING_TABLE = 'SET_LOADING_TABLE'
export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const SET_SUBMIT_EDIT_USER = 'SET_SUBMIT_EDIT_USER'
export const GET_LIST_USER_SEARCH = 'GET_LIST_USER_SEARCH'

//SAGA

export const GET_USER_LOGIN_SAGA = 'GET_USER_LOGIN_SAGA'
export const POST_USER_SIGNUP_SAGA = 'POST_USER_SIGNUP_SAGA'
export const GET_LIST_USER_SAGA = 'GET_LIST_USER_SAGA'
export const DELETE_USER_SAGA = 'DELETE_USER_SAGA'
export const GET_USER_DETAIL_SAGA = 'GET_USER_DETAIL_SAGA'
export const SUBMIT_EDIT_USER_SAGA = 'SUBMIT_EDIT_USER_SAGA'
export const GET_LIST_USER_SEARCH_SAGA = 'GET_LIST_USER_SEARCH_SAGA'